name: CI (Monorepo)

on:
  push: { branches: [main] }
  pull_request: { branches: [main] }
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  security-events: write

env:
  SONAR_ENABLED: ${{ vars.SONAR_ENABLED || 'false' }}

jobs:
  detect-changes:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Prepare runner caches
        run: |
          echo "AGENT_TOOLSDIRECTORY=$GITHUB_WORKSPACE/.runner-toolcache" >> $GITHUB_ENV
          echo "RUNNER_TOOL_CACHE=$GITHUB_WORKSPACE/.runner-toolcache"     >> $GITHUB_ENV
          echo "RUNNER_TEMP=$GITHUB_WORKSPACE/.runner-tmp"                 >> $GITHUB_ENV
          mkdir -p "$GITHUB_WORKSPACE/.runner-toolcache" "$GITHUB_WORKSPACE/.runner-tmp"
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            api: ['apps/api-gateway-node/**', 'libs/**']
            pay: ['apps/payments-python/**', 'libs/**']
            ord: ['apps/orders-java/**', 'libs/**']
    outputs:
      api:  ${{ steps.filter.outputs.api }}
      pay:  ${{ steps.filter.outputs.pay }}
      ord:  ${{ steps.filter.outputs.ord }}

  api:
    needs: detect-changes
    if: needs.detect-changes.outputs.api == 'true'
    runs-on: self-hosted
    env:
      IMAGE: ghcr.io/${{ github.repository_owner }}/api-gateway-node
      TAG: ${{ github.sha }}
    steps:
      - uses: actions/checkout@v4
      - name: Prepare runner caches
        run: |
          echo "AGENT_TOOLSDIRECTORY=$GITHUB_WORKSPACE/.runner-toolcache" >> $GITHUB_ENV
          echo "RUNNER_TOOL_CACHE=$GITHUB_WORKSPACE/.runner-toolcache"     >> $GITHUB_ENV
          echo "RUNNER_TEMP=$GITHUB_WORKSPACE/.runner-tmp"                 >> $GITHUB_ENV
          mkdir -p "$GITHUB_WORKSPACE/.runner-toolcache" "$GITHUB_WORKSPACE/.runner-tmp"

      - uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install
        working-directory: apps/api-gateway-node
        run: npm install --no-audit --no-fund

      - name: Lint
        working-directory: apps/api-gateway-node
        run: npm run lint

      - name: Test
        working-directory: apps/api-gateway-node
        run: npm test

      # ---------- Sonar (native CLI, not container action) ----------
      - name: Ping SonarQube
        if: env.SONAR_ENABLED == 'true'
        run: curl -fsSL -o /dev/null "${{ vars.SONAR_HOST_URL }}/api/server/version"

      - name: Install Sonar Scanner (macOS)
        if: env.SONAR_ENABLED == 'true' && !startsWith(runner.os, 'Linux')
        run: |
          set -euo pipefail
          SCAN_VER=5.0.1.3006
          URL="https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-${SCAN_VER}-macosx.zip"
          DEST="$RUNNER_TOOL_CACHE/sonar"
          mkdir -p "$DEST"
          rm -rf "$DEST/sonar-scanner-${SCAN_VER}-macosx" || true
          curl -fsSL "$URL" -o scanner.zip
          unzip -qo scanner.zip -d "$DEST"
          echo "$DEST/sonar-scanner-${SCAN_VER}-macosx/bin" >> "$GITHUB_PATH"

      - name: SonarQube Scan (CLI)
        if: env.SONAR_ENABLED == 'true'
        working-directory: apps/api-gateway-node
        run: |
          sonar-scanner \
            -Dsonar.host.url="${{ vars.SONAR_HOST_URL }}" \
            -Dsonar.login="${{ secrets.SONAR_TOKEN }}"

      - name: SonarQube Quality Gate
        if: env.SONAR_ENABLED == 'true'
        uses: SonarSource/sonarqube-quality-gate-action@v1.1.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
        with:
          scanMetadataReportFile: apps/api-gateway-node/.scannerwork/report-task.txt
      # --------------------------------------------------------------

      - name: Login GHCR
        if: github.event_name == 'push'
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Build & Push
        if: github.event_name == 'push'
        run: |
          docker build -t $IMAGE:$TAG apps/api-gateway-node
          docker tag $IMAGE:$TAG $IMAGE:dev
          docker push $IMAGE:$TAG
          docker push $IMAGE:dev

  pay:
    needs: detect-changes
    if: needs.detect-changes.outputs.pay == 'true'
    runs-on: self-hosted
    env:
      IMAGE: ghcr.io/${{ github.repository_owner }}/payments-python
      TAG: ${{ github.sha }}
    steps:
      - uses: actions/checkout@v4
      - name: Prepare runner caches
        run: |
          echo "AGENT_TOOLSDIRECTORY=$GITHUB_WORKSPACE/.runner-toolcache" >> $GITHUB_ENV
          echo "RUNNER_TOOL_CACHE=$GITHUB_WORKSPACE/.runner-toolcache"     >> $GITHUB_ENV
          echo "RUNNER_TEMP=$GITHUB_WORKSPACE/.runner-tmp"                 >> $GITHUB_ENV
          mkdir -p "$GITHUB_WORKSPACE/.runner-toolcache" "$GITHUB_WORKSPACE/.runner-tmp"

      # 👇 setup-python now sees the toolcache under the workspace
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - run: pip install --no-cache-dir pytest
      - run: pytest -q || true

      # ---------- Sonar ----------
      - name: Ping SonarQube
        if: env.SONAR_ENABLED == 'true'
        run: curl -fsSL -o /dev/null "${{ vars.SONAR_HOST_URL }}/api/server/version"

      - name: Install Sonar Scanner (macOS)
        if: env.SONAR_ENABLED == 'true' && !startsWith(runner.os, 'Linux')
        run: |
          set -euo pipefail
          SCAN_VER=5.0.1.3006
          URL="https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-${SCAN_VER}-macosx.zip"
          DEST="$RUNNER_TOOL_CACHE/sonar"
          mkdir -p "$DEST"
          rm -rf "$DEST/sonar-scanner-${SCAN_VER}-macosx" || true
          curl -fsSL "$URL" -o scanner.zip
          unzip -qo scanner.zip -d "$DEST"
          echo "$DEST/sonar-scanner-${SCAN_VER}-macosx/bin" >> "$GITHUB_PATH"

      - name: SonarQube Scan (CLI)
        if: env.SONAR_ENABLED == 'true'
        working-directory: apps/payments-python
        run: |
          sonar-scanner \
            -Dsonar.host.url="${{ vars.SONAR_HOST_URL }}" \
            -Dsonar.login="${{ secrets.SONAR_TOKEN }}"

      - name: SonarQube Quality Gate
        if: env.SONAR_ENABLED == 'true'
        uses: SonarSource/sonarqube-quality-gate-action@v1.1.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
        with:
          scanMetadataReportFile: apps/payments-python/.scannerwork/report-task.txt
      # ---------------------------

      - name: Login GHCR
        if: github.event_name == 'push'
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Build & Push
        if: github.event_name == 'push'
        run: |
          docker build -t $IMAGE:$TAG apps/payments-python
          docker tag $IMAGE:$TAG $IMAGE:dev
          docker push $IMAGE:$TAG
          docker push $IMAGE:dev

  ord:
    needs: detect-changes
    if: needs.detect-changes.outputs.ord == 'true'
    runs-on: self-hosted
    env:
      IMAGE: ghcr.io/${{ github.repository_owner }}/orders-java
      TAG: ${{ github.sha }}
    steps:
      - uses: actions/checkout@v4
      - name: Prepare runner caches
        run: |
          echo "AGENT_TOOLSDIRECTORY=$GITHUB_WORKSPACE/.runner-toolcache" >> $GITHUB_ENV
          echo "RUNNER_TOOL_CACHE=$GITHUB_WORKSPACE/.runner-toolcache"     >> $GITHUB_ENV
          echo "RUNNER_TEMP=$GITHUB_WORKSPACE/.runner-tmp"                 >> $GITHUB_ENV
          mkdir -p "$GITHUB_WORKSPACE/.runner-toolcache" "$GITHUB_WORKSPACE/.runner-tmp"

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install Maven
        run: |
          set -euo pipefail
          MAVEN_VERSION=3.9.9
          URL="https://archive.apache.org/dist/maven/maven-3/${MAVEN_VERSION}/binaries/apache-maven-${MAVEN_VERSION}-bin.tar.gz"
          curl -fsSL "$URL" -o maven.tgz
          DEST="$RUNNER_TOOL_CACHE/maven"
          mkdir -p "$DEST"
          rm -rf "$DEST/apache-maven-${MAVEN_VERSION}" || true
          tar -xzf maven.tgz -C "$DEST"
          echo "$DEST/apache-maven-${MAVEN_VERSION}/bin" >> "$GITHUB_PATH"

      - name: Verify Maven
        run: mvn -v

      - name: Build orders-java
        run: |
          cd apps/orders-java
          mvn -q -DskipTests=true package

      # ---------- Sonar ----------
      - name: Ping SonarQube
        if: env.SONAR_ENABLED == 'true'
        run: curl -fsSL -o /dev/null "${{ vars.SONAR_HOST_URL }}/api/server/version"

      - name: Install Sonar Scanner (macOS)
        if: env.SONAR_ENABLED == 'true' && !startsWith(runner.os, 'Linux')
        run: |
          set -euo pipefail
          SCAN_VER=5.0.1.3006
          URL="https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-${SCAN_VER}-macosx.zip"
          DEST="$RUNNER_TOOL_CACHE/sonar"
          mkdir -p "$DEST"
          rm -rf "$DEST/sonar-scanner-${SCAN_VER}-macosx" || true
          curl -fsSL "$URL" -o scanner.zip
          unzip -qo scanner.zip -d "$DEST"
          echo "$DEST/sonar-scanner-${SCAN_VER}-macosx/bin" >> "$GITHUB_PATH"

      - name: SonarQube Scan (CLI)
        if: env.SONAR_ENABLED == 'true'
        working-directory: apps/orders-java
        run: |
          sonar-scanner \
            -Dsonar.host.url="${{ vars.SONAR_HOST_URL }}" \
            -Dsonar.login="${{ secrets.SONAR_TOKEN }}"

      - name: SonarQube Quality Gate
        if: env.SONAR_ENABLED == 'true'
        uses: SonarSource/sonarqube-quality-gate-action@v1.1.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
        with:
          scanMetadataReportFile: apps/orders-java/.scannerwork/report-task.txt
      # ---------------------------

      - name: Login GHCR
        if: github.event_name == 'push'
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Build & Push
        if: github.event_name == 'push'
        run: |
          docker build -t $IMAGE:$TAG apps/orders-java
          docker tag $IMAGE:$TAG $IMAGE:dev
          docker push $IMAGE:$TAG
          docker push $IMAGE:dev
